"""raw observation capture

Revision ID: 4c63f390aa9e
Revises: d1a4b27ae9cb
Create Date: 2026-09-01 08:12:52.013516
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4c63f390aa9e'
down_revision = 'd1a4b27ae9cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_observations', schema=None) as batch_op:
        batch_op.create_index('ix_raw_site_created', ['site_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_site_created')

    op.drop_table('raw_observations')
    # ### end Alembic commands ###
