"""initial store schema

Revision ID: d1a4b27ae9cb
Revises: 
Create Date: 2026-08-27 13:33:15.759908
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd1a4b27ae9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_syncs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.String(length=100), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend', 'object_type', 'local_id', name='uq_backend_sync_local')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('collectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_collector_name')
    )
    op.create_table('credential_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('secret_refs', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('snmp', 'fortios')", name='ck_credential_kind'),
    sa.CheckConstraint("storage IN ('inline', 'env_ref')", name='ck_credential_storage'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_credential_name')
    )
    op.create_table('dhcp_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('firewall', sa.String(length=200), nullable=True),
    sa.Column('interface', sa.String(length=100), nullable=True),
    sa.Column('start_ip', sa.String(length=45), nullable=False),
    sa.Column('end_ip', sa.String(length=45), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'start_ip', 'end_ip', name='uq_pool_range')
    )
    op.create_table('prefixes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=49), nullable=False),
    sa.Column('source_device', sa.String(length=200), nullable=True),
    sa.Column('source_interface', sa.String(length=100), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'cidr', name='uq_prefix_cidr')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'vid', name='uq_vlan_vid')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firewalls_ok', sa.Integer(), nullable=False),
    sa.Column('firewalls_failed', sa.Integer(), nullable=False),
    sa.Column('switches_ok', sa.Integer(), nullable=False),
    sa.Column('switches_failed', sa.Integer(), nullable=False),
    sa.Column('mac_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('ok', 'degraded', 'failed', 'idle', 'error', 'skipped')", name='ck_run_status'),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_site_started', ['site_id', 'started_at'], unique=False)

    op.create_table('targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('credential_profile_id', sa.Integer(), nullable=True),
    sa.Column('vendor_override', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('snmp', 'fortios')", name='ck_target_method'),
    sa.CheckConstraint("source IN ('manual', 'imported', 'seed')", name='ck_target_source'),
    sa.ForeignKeyConstraint(['credential_profile_id'], ['credential_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'address', 'method', name='uq_target_address')
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('static_reservation', sa.Boolean(), nullable=False),
    sa.Column('switch_name', sa.String(length=200), nullable=True),
    sa.Column('switch_port', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.String(length=20), nullable=True),
    sa.Column('firewall', sa.String(length=200), nullable=True),
    sa.Column('firewall_interface', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'offline', 'deprecated')", name='ck_endpoint_status'),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'mac', name='uq_endpoint_mac')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index('ix_endpoints_last_seen', ['site_id', 'last_seen_at'], unique=False)

    op.create_table('endpoint_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('prefix_len', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('active', 'dhcp', 'reserved')", name='ck_address_kind'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'ip', name='uq_endpoint_ip')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_site_created', ['site_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_site_created')

    op.drop_table('events')
    op.drop_table('endpoint_addresses')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index('ix_endpoints_last_seen')

    op.drop_table('endpoints')
    op.drop_table('targets')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_site_started')

    op.drop_table('runs')
    op.drop_table('vlans')
    op.drop_table('prefixes')
    op.drop_table('dhcp_pools')
    op.drop_table('credential_profiles')
    op.drop_table('collectors')
    op.drop_table('api_keys')
    op.drop_table('sites')
    op.drop_table('backend_syncs')
    # ### end Alembic commands ###
